name: convex
description: small set of convenient extensions for dart projects to reduce code
version: 0.0.3+1
repository: https://github.com/saklani/convex

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0